package org.economicsl

import java.util.UUID

import org.economicsl.core.Quantity


package object settlement {

  type AssetHoldings = Map[UUID, Quantity]

  /** Block is a collection of transactions generated by settling a particular contract. */
  type Block = Stream[Transaction]

}
